Repository ministryofjustice/laa-fee-calculator, pull requests merged in 2022-05, with the labels that each got.

#222 [CFP-399] Replace django-rest-swagger with drf-spectacular
  fee_calculator/apps/api/filters.py
  fee_calculator/apps/api/serializers.py
  fee_calculator/apps/api/urls.py
  fee_calculator/apps/api/views.py
  fee_calculator/apps/calculator/models.py
  fee_calculator/apps/calculator/tests/__init__.py
  fee_calculator/settings/base.py
  requirements/base.txt
Labels: approved, in test

#232 Update dependabot reviewers
  .github/dependabot.yml
Labels: ready for review

#234 Update DEVELOPMENT.md to reflect Django upgrade
  docs/DEVELOPMENT.md
Labels: ready for review

#236 CFP-260 Use Alpine instead of Ubuntu for docker builds
  Dockerfile
Labels: approved
